### PR TITLE
time field: fix which views require time in points and which ones don't

### LINKED ISSUE #31: warning on timeField makes barchart not render anything
The barchart example from our documentation: http://juttle.github.io/juttle-viz/charts/barchart/ which is the following juttle:

```
read stochastic -source 'cdn' -nhosts 10 -from :10 minutes before 2014-01-01: -to :2014-01-01: -source_type 'metrics' name = 'cpu'
| filter name = 'cpu'
| reduce value = avg(value) by host
| sort value -desc
| view barchart -o {
    categoryField: 'host',
    valueField: 'value',
    title: 'Average CPU % per host for last 10 minutes',
    yScales: {
      primary: {
        tickFormat: '%'
      }
    },
    tooltip: {
      valueFormat: '%'
    }
  }
```

This didn't produce a warning at all (or maybe I didn't notice it ) but it did in fact produce the expected bars and now there's the warning `"The "timeField" you specified does not contain valid values."` and the SVG element with the barchart has the display set to `none`.

### PR DESCRIPTION
**Pull request by go-oleg**
There was some code removed in #25 that related to whether a given view requires time in points or not removed. The result was that all views require time in points which is incorrect.

Bring the code back and add tests to make sure views don't complain about points without time.

Fixes #31.

@rlgomes @mnibecker

### CODE REVIEW

File: src/views/events.js [hunk 1]
```diff
@@ -141,6 +141,16 @@ var EventsView = JuttleView.extend({
         this.target.stream_end();
     },
 
+    _validateTimeField : function(time) {
+        // if in timechart overlay, timeField needs to actually be a Date
+        if (this._targetView) {
+            return _.isDate(time) && !_.isNaN(time.getTime());
```
Comment (rlgomes) [inline src/views/events.js:147]: If I learned anything from @davidvgalbraith is that checking for NaN the quickest and easiest way is done with `X === X`

Comment (rlgomes) [inline src/views/events.js:147]: In this case `!(X===X)`

**Comment by rlgomes** [comment]
Looks good (soon enough you won't be able to use them double quotes though ;) )

File: src/views/events.js (hunk 1 above)
Comment (go-oleg) [inline src/views/events.js:147]: Thats close to what underscore does: http://underscorejs.org/docs/underscore.html#section-145

**Comment by go-oleg** [comment]
I am looking forward to being properly limited to best practices.

File: src/views/events.js (hunk 1 above)
Comment (davidvgalbraith) [inline src/views/events.js:147]: The `_.isNumber` half of what they do is useless and slow as molasses. If performance isn't important though `_.isNaN` has the readability edge.

Comment (go-oleg) [inline src/views/events.js:147]: molasses has been known to travel at speeds of up to [35 mph](https://en.wikipedia.org/wiki/Great_Molasses_Flood), but point taken, thx for the heads up.
